config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do
    namespace :v1 do
      get 'combos' => 'combos#index', :as => 'combos'
      get 'products' => 'products#index', :as => 'products' 
      get 'categories' => 'categories#index', :as => 'categories'
      get 'brands' => 'brands#index', :as => 'brands' 
      get 'orders' => 'orders#index', :as => 'orders'
      post 'orders' => 'orders#create'
      post 'users' => 'users#create'
      post 'sessions' => 'sessions#create'
      delete 'sessions' => 'sessions#destroy'
      get 'active_schedules' => 'active_schedule#index', :as => 'active_schedules'
      post 'device_tokens' => 'device_tokens#create'
    end
    namespace :v2 do
      get 'closest_company' => 'companies#closest_company', :as => 'closest_company'
      get 'valid_coupon' => 'coupons#valid_coupon', :as => 'valid_coupon'
      get 'categories' => 'categories#index', :as => 'categories'
      get 'brand_products' => 'brand_products#index', :as => 'brand_products'
      get 'brands' => 'brands#index', :as => 'brands' 
      post 'sessions', to: 'sessions#create'
      delete 'sessions', to: 'sessions#destroy'
      post 'registrations', to: 'registrations#create'
      get 'active_schedules' => 'active_schedule#index', :as => 'active_schedules'
      post 'device_tokens' => 'device_tokens#create'
      post 'payments/register_card' => 'payments#register_card'
      post 'net_promoting_scores' => 'net_promoting_scores#create'
      get 'orders' => 'orders#index'
      patch 'orders/:id' => 'orders#change_state'
      resources :companies do
        resources :products, only: [:index]
        resources :combos, only: [:index]
        get 'find_items' => 'companies#find_items', :as => 'find_items'
        post 'orders' => 'orders#create'
        get 'company_banners' => 'companies#company_banners', :as => 'company_banners'
      end
      get 'fidelity_points' => 'me#fidelity_points', :as => 'fidelity_points'
      get 'my_orders' => 'me#my_orders', :as => 'my_orders'
      get 'credit_cards' => 'me#credit_cards', :as => 'credit_cards'
      delete 'credit_cards', to: 'payments#delete_card'
    end
  end
end

app/views/new_orders/_index.html.erb
<div id="order-notifications-table">
    <div id="orders_list">
        <%= render partial: "new_orders/orders_list", :locals => {:orders => orders}%>
    </div>
</div>

app/views/new_orders/_orders_list.html.erb
<% if flash[:notice] %>
  <div class="flash-message <%= notice ? "notice" : ""%><%= alert ? "error" : ""%>">
    <div class="clearfix">
      <div class="grid_12">
        <% if notice %>
          <p><%= notice %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<ul class="notifications-list">
    <% orders.each do |order| %>
      <li class="notification-detail">
        <%= link_to "Orden ##{order.id} pedida el #{order.created_at.strftime("%d de %b")} a las #{order.created_at.strftime("%R")} para la companía #{order.company.name}",  admin_order_path(order), :class => 'btn btn-mini', :target => "_blank" %>
      </li>
    <% end %>
</ul>